{% set version = "2022a0" %}

package:
  name: tzdata
  version: {{ version }}

source:
  - url: https://data.iana.org/time-zones/releases/tzdata{{ version }}.tar.gz
    sha256: 8510630bc01a691aceca24a79262f758edc6af36222773f8653ef4285ad4aebd
  - url: https://data.iana.org/time-zones/releases/tzcode{{ version }}.tar.gz
    sha256: 8510630bc01a691aceca24a79262f758edc6af36222773f8653ef4285ad4aebd

build:
  number: 0
  noarch: generic
  # The recipe assumes building on Linux, but we don't have "skip" active since
  # the linter will complain with "`noarch` packages can't have selectors".
  # skip: True  # [not linux]
  ignore_run_exports:
    - libgcc-ng

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]
    - m2-make  # [win]
  host:
  run:

test:
  requires:
    - python <3.10
  commands:
    # Make sure we only package zoneinfo and nothing else.
    - |
      dirs="$(
        find "${PREFIX}" -mindepth 1 -maxdepth 2 \
        \! -path "${PREFIX}/share" \! -path "${PREFIX}/conda-meta*"
      )"
      test "${dirs}" = "${PREFIX}/share/zoneinfo"
    # Make sure we only package timezone information files.
    - |
      heads="$(
        find "${PREFIX}/share/zoneinfo" -type f \
          \! -name \*.zi \! -name \*.tab \! -name leapseconds \
          -exec head -c4 {} \; -printf \\n \
          | uniq
      )"
      test "${heads}" = TZif  # [not (osx-64 or osx-arm64)]

    # OSX does not have the '-printf' operator.
    - |
      heads="$(
        find "${PREFIX}/share/zoneinfo" -type f \
          \! -name \*.zi \! -name \*.tab \! -name leapseconds \
          -exec head -c4 {} \; -print0 \
          | uniq \
          | cut -c1-4 \
      )"
      test "${heads}" = TZif  # [osx-64 or osx-arm64]


about:
  home: https://www.iana.org/time-zones
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  license: Public-Domain AND BSD-3-clause
  license_file: LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo)

  description: |
    The Time Zone Database (called tz, tzdb or zoneinfo) contains code and
    data that represent the history of local time for many representative
    locations around the globe.  It is updated periodically to reflect
    changes made by political bodies to time zone boundaries, UTC offsets,
    and daylight-saving rules.

extra:
  recipe-maintainers:
    - ocefpaf
    - mbargull
    - pganssle
