{% set version = "2022f" %}

package:
  name: tzdata
  version: {{ version }}

source:
  - url: https://data.iana.org/time-zones/releases/tzdata{{ version }}.tar.gz
    sha256: 9990d71f675d212567b931fe8aae1cab7027f89fefb8a79d808a6933a67af000
  - url: https://data.iana.org/time-zones/releases/tzcode{{ version }}.tar.gz
    sha256: e4543e90f84f91fa82809ea98930052fdbc13880c8a623ee3a4eaa42f8a64c15

build:
  number: 0
  noarch: generic
  # This package needs to be noarch because it uses POSIX system APIs.
  # The Windows build will be skipped when built to avoid Prefect failures.
  # There is no Windows port available and porting to Windows is not trivial.

  # However, the compiled package can be used on Windows.
  skip: True  # [win]
  ignore_run_exports:
    - libgcc-ng

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
  run:

about:
  home: https://www.iana.org/time-zones
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  license: CC-PDDC OR BSD-3-Clause
  license_file: LICENSE
  license_url: https://github.com/eggert/tz/blob/main/LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo)

  description: |
    The Time Zone Database (called tz, tzdb or zoneinfo) contains code and
    data that represent the history of local time for many representative
    locations around the globe.  It is updated periodically to reflect
    changes made by political bodies to time zone boundaries, UTC offsets,
    and daylight-saving rules.

extra:
  recipe-maintainers:
    - ocefpaf
    - mbargull
    - pganssle
