{% set version = "2022c" %}

package:
  name: tzdata
  version: {{ version }}

source:
  - url: https://data.iana.org/time-zones/releases/tzdata{{ version }}.tar.gz
    sha256: 6974f4e348bf2323274b56dff9e7500247e3159eaa4b485dfa0cd66e75c14bfe
  - url: https://data.iana.org/time-zones/releases/tzcode{{ version }}.tar.gz
    sha256: 3e7ce1f3620cc0481907c7e074d69910793285bffe0ca331ef1a6d1ae3ea90cc

build:
  number: 0
  noarch: generic
  # The recipe assumes building on Linux, but we don't have "skip" active since
  # the linter will complain with "`noarch` packages can't have selectors".
  # skip: True  # [not linux]
  ignore_run_exports:
    - libgcc-ng

requirements:
  build:
    - {{ compiler('c') }}
    - make  # [not win]
    - m2-make  # [win]
  host:
  run:

test:
  commands:
    # Make sure we only package timezone information files.
    - |
      heads="$(
        find "${PREFIX}/share/zoneinfo" -type f \
          \! -name \*.zi \! -name \*.tab \! -name leapseconds \
          -exec head -c4 {} \; -printf \\n \
          | uniq
      )"                      # [linux]
      test "${heads}" = TZif  # [linux]

    # OSX does not have the '-printf' operator.
    - |
      heads="$(
        find "${PREFIX}/share/zoneinfo" -type f \
          \! -name \*.zi \! -name \*.tab \! -name leapseconds \
          -exec head -c4 {} \; -print0 \
          | uniq \
          | cut -c1-4 \
      )"                      # [osx-64 or osx-arm64]
      test "${heads}" = TZif  # [osx-64 or osx-arm64]


about:
  home: https://www.iana.org/time-zones
  dev_url: https://github.com/eggert/tz
  doc_url: https://data.iana.org/time-zones/tz-link.html
  license: CC-PDDC OR BSD-3-Clause
  license_file: LICENSE
  license_url: https://github.com/eggert/tz/blob/main/LICENSE
  summary: The Time Zone Database (called tz, tzdb or zoneinfo)

  description: |
    The Time Zone Database (called tz, tzdb or zoneinfo) contains code and
    data that represent the history of local time for many representative
    locations around the globe.  It is updated periodically to reflect
    changes made by political bodies to time zone boundaries, UTC offsets,
    and daylight-saving rules.

extra:
  recipe-maintainers:
    - ocefpaf
    - mbargull
    - pganssle
